C     Last change:  BCM  12 Mar 98   12:35 pm
**==tdlom.f    processed by SPAG 4.03F  at 10:51 on 21 Apr 1994
      SUBROUTINE tdlom(Stcsi,Stocal,Sprior,Factd,First,Last,Muladd,
     &                 Adjtd,Adjtmp)
      IMPLICIT NONE
c     ------------------------------------------------------------------
c     This routine removes length of month adjustment factors from the
c     prior adjustment factors (Sprior) and combines them with the
c     trading day effect generated by the regARIMA model (Factd) if this
c     effect is to be removed from the series.
c     Add Adjtmp as a argument, which is now computed in another
c     subroutine (BCM Oct 2009)
c     ------------------------------------------------------------------
      INCLUDE 'srslen.prm'
      INCLUDE 'prior.prm'
      INCLUDE 'prior.cmn'
      INCLUDE 'priadj.cmn'
      INCLUDE 'priusr.cmn'
      INCLUDE 'adj.cmn'
c      INCLUDE 'lzero.cmn'
c     ------------------------------------------------------------------
      DOUBLE PRECISION Stcsi,Stocal,Adjtmp,Sprior,Factd
      INTEGER Muladd,First,Last,Adjtd
      DIMENSION Stcsi(PLEN),Stocal(PLEN),Adjtmp(PLEN),Sprior(PLEN),
     &          Factd(PLEN)
c     ------------------------------------------------------------------
c     Combine LOM factors with model based trading day effects by
c     multiplying series by combined prior and LOM factors and dividing
c     out prior effects.
c     ------------------------------------------------------------------
      IF(Adjtd.eq.1)THEN
       CALL addmul(Factd,Factd,Sprior,First,Last)
       CALL divsub(Factd,Factd,Adjtmp,First,Last)
c     ------------------------------------------------------------------
c     Remove Length of Month effect from Stocal (Oct 2009 BCM)
c     ------------------------------------------------------------------
       CALL divsub(Stocal,Stocal,Sprior,First,Last)
       CALL addmul(Stocal,Stocal,Adjtmp,First,Last)
c     ------------------------------------------------------------------
c     Reset prior effects to be original prior factors.
c     ------------------------------------------------------------------
       CALL copy(Adjtmp(Setpri),Nadj,1,Sprior(Setpri))
       Priadj=0-Priadj
      ELSE
c     ------------------------------------------------------------------
c     Else, reset original series, remove LOM from prior effects and
c     adjust original series by prior effects.
c     ------------------------------------------------------------------
c     Also, reset calendar adjusted original series, remove LOM from
c     prior effects and adjust original series by prior effects.
c     BCM May 2006
c     ------------------------------------------------------------------
       CALL addmul(Stcsi,Stcsi,Sprior,First,Last)
       CALL addmul(Stocal,Stocal,Sprior,First,Last)
       CALL copy(Adjtmp(Setpri),Nadj,1,Sprior(Setpri))
       CALL divsub(Stcsi,Stcsi,Sprior,First,Last)
       CALL divsub(Stocal,Stocal,Sprior,First,Last)
c     ------------------------------------------------------------------
       Priadj=0
      END IF
c     ------------------------------------------------------------------
      RETURN
      END
