      SUBROUTINE errhdr
      IMPLICIT NONE
C-----------------------------------------------------------------------
c     print a header in the error file to denote that this error was
c     generated by a particular hidden run from the sliding spans or
c     revision history analysis.
C-----------------------------------------------------------------------
      INCLUDE 'srslen.prm'
      INCLUDE 'notset.prm'
      INCLUDE 'ssap.prm'
      INCLUDE 'ssft.cmn'
      INCLUDE 'rev.prm'
      INCLUDE 'rev.cmn'
      INCLUDE 'hiddn.cmn'
      INCLUDE 'units.cmn'
      INCLUDE 'htmlout.cmn'
C-----------------------------------------------------------------------
      IF(Issap.lt.2.and.Irev.lt.4)RETURN
      IF((Issap.eq.2.and.Ierhdr.eq.Icol).or.
     &   (Irev.eq.4.and.Ierhdr.eq.Revptr))RETURN
C-----------------------------------------------------------------------
      IF(Issap.eq.2)THEN
       CALL writTag(Mt2,Charhr)
       WRITE(Mt2,1020)Icol
       Ierhdr=Icol
      ELSE IF(Issap.eq.3.and.Ierhdr.ne.NOTSET)THEN
       CALL writTag(Mt2,Charhr)
       CALL mkPOneLine(Mt2,'@','&nbsp;')
       Ierhdr=NOTSET
      ELSE IF(Irev.eq.4)THEN
       CALL writTag(Mt2,Charhr)
       WRITE(Mt2,1030)Crvend(1:Nrvend)
       Ierhdr=Revptr
      ELSE IF(Irev.eq.5.and.Ierhdr.ne.NOTSET)THEN
       CALL writTag(Mt2,Charhr)
       CALL mkPOneLine(Mt2,'@','&nbsp;')
       Ierhdr=NOTSET
      END IF
C-----------------------------------------------------------------------
 1020 FORMAT(' <h2> Error/Warning Messages for sliding span # ',i1,':',
     &       '</h2>')
 1030 FORMAT(' <h2> Error/Warning Messages for history run ending ',a,
     &       ':</h2>')
      RETURN
      END
      